apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    protocol: {{ .Values.service.protocol }}
    targetPort: 3111
  selector:
    app: techtrends
  type: {{ .Values.service.type }} 
